 on:
  push:
     branches: [ QA ]
  pull_request:
     branches: [ QA ]
    
    
 jobs:
   build:
    runs-on: ubuntu-latest
    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: WhatAmIDoing&Wrong
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"
    steps:
    - name: list container images
      run: docker ps -a
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./*.sql
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./*.sql
    - name: Restore donettool
      run: dotnet tool install --global dotnet-ef
      working-directory: ./*.sql
    - name: update database
      run: dotnet-ef database update --no-build
      working-directory: ./*.sql
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./*.sql
    
    
        
        
